version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: otto_shoes_db
    restart: always
    environment:
      POSTGRES_USER: otto_admin
      POSTGRES_PASSWORD: otto_secure_password
      POSTGRES_DB: otto_ims
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: