# Generated by Django 6.0.5 on 2026-06-05 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_deleted", models.SmallIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "delivery_types",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="encoded_by",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="is_pickup",
        ),
        migrations.AddField(
            model_name="transaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="delivery_type_snapshot",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_deleted",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="delivery_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="sales.deliverytype",
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
