# Generated by Django 6.0.5 on 2026-06-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_deliverytype_alter_transaction_encoded_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_pickup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("item_description", models.TextField(blank=True, default="")),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("delivery_address", models.TextField(blank=True, default="")),
                ("delivery_type_snapshot", models.CharField(max_length=50)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("is_pickup", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Ready for Pickup", "Ready for Pickup"),
                            ("In Transit", "In Transit"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_record",
                        to="sales.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_records",
                "ordering": ["-scheduled_at", "-created_at"],
            },
        ),
    ]
