# Generated by Django 6.0.5 on 2026-06-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_transaction_is_pickup_transaction_scheduled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrecord",
            name="delivery_id",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
