# Generated by Django 6.0.5 on 2026-06-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_deliveryrecord_delivery_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sizetype",
            name="unit",
            field=models.CharField(default="sqr", max_length=10),
        ),
    ]
